import { Dimensions, StyleSheet } from "react-native";
import { Styles } from "@/src/types/friend";

export const colors = {
  background: "#0F1623",
  cardBackground: "#1A2437",
  cardBackgroundAlt: "#202B41",
  primary: "#4F6EF7",
  primaryGradientStart: "#4F6EF7",
  primaryGradientEnd: "#55ACEE",
  secondary: "#9C56DD",
  secondaryGradientStart: "#9C56DD",
  secondaryGradientEnd: "#C164FF",
  success: "#0ACF83",
  successGradientStart: "#0ACF83",
  successGradientEnd: "#4CD964",
  danger: "#FF3B5F",
  dangerGradientStart: "#FF3B5F",
  dangerGradientEnd: "#FF5E3A",
  white: "#FFFFFF",
  lightGray: "#9BA3B2",
  borderColor: "#2A3343",
  highlight: "#FFD60A",
  shimmerStart: "rgba(255,255,255,0.0)",
  shimmerEnd: "rgba(255,255,255,0.15)",
};

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create<Styles>({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 16,
  },
  headerGradient: {
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginHorizontal: -16,
    paddingHorizontal: 16,
    marginTop: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
  },
  backButton: {
    padding: 10,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
  },
  headerTitle: {
    color: colors.white,
    fontSize: 22,
    fontWeight: "bold",
    marginLeft: 16,
  },
  headerBadge: {
    backgroundColor: colors.primary,
    borderRadius: 15,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginLeft: 10,
    borderWidth: 2,
    borderColor: colors.white,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  headerBadgeText: {
    color: colors.white,
    fontWeight: "bold",
    fontSize: 12,
  },
  searchContainer: {
    borderRadius: 12,
    marginVertical: 16,
    overflow: "hidden",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  searchBlur: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    paddingLeft: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    gap: 10,
  },
  searchIcon: {
    marginRight: 10,
    backgroundColor: "transparent"
  },
  input: {
    flex: 1,
    color: colors.white,
    fontSize: 16,
    lineHeight: 28,
    paddingVertical: 14,
    paddingLeft: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "transparent",
    backgroundColor: "transparent",
    // includeFontPadding: false,
    textAlignVertical: "center",
  },
  clearButton: {
    padding: 8,
    // backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 20,
    marginHorizontal: 10,
  },
  tabContainer: {
    flexDirection: "row",
    marginVertical: 16,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    padding: 0,
    position: "relative",
    height: 50,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  tabIndicator: {
    position: "absolute",
    top: 1,
    width: "46%",
    height: "95%",
    borderRadius: 8,
    zIndex: 0,
  },
  tabText: {
    color: colors.lightGray,
    fontWeight: "500",
    fontSize: 14,
    margin: 2
  },
  activeTabText: {
    color: colors.white,
    fontWeight: "bold",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: colors.lightGray,
    marginTop: 16,
    fontSize: 16,
  },
  resultsContainer: {
    flex: 1,
  },
  resultTitle: {
    color: colors.white,
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 16,
  },
  resultCount: {
    color: colors.primary,
    fontWeight: "normal",
  },
  listContent: {
    paddingBottom: 20,
  },
  userCard: {
    flexDirection: "row",
    backgroundColor: colors.cardBackground,
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    alignItems: "center",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  avatarContainer: {
    position: "relative",
  },
  avatar: {
    width: 55,
    height: 55,
    borderRadius: 28,
    marginRight: 12,
    borderWidth: 2,
    borderColor: colors.primaryGradientEnd,
  },
  onlineIndicator: {
    position: "absolute",
    bottom: 0,
    right: 12,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: colors.success,
    borderWidth: 2,
    borderColor: colors.cardBackground,
  },
  userInfo: {
    flex: 1,
    justifyContent: "center",
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  name: {
    color: colors.white,
    fontWeight: "600",
    fontSize: 16,
  },
  username: {
    color: colors.lightGray,
    fontSize: 14,
    marginTop: 2,
  },
  sentRequest: {
    backgroundColor: colors.dangerGradientEnd,
    borderRadius: 16,
    padding: 14,
  },
  sentRequestText: {
    color: colors.white,
    fontWeight: "600",
    fontSize: 13,
    marginLeft: 6,
  },
  receivedRequest: {
    backgroundColor: colors.primaryGradientEnd,
    borderRadius: 16,
    padding: 14,
    display: "flex",
  },
  receivedRequestText: {
    color: colors.white,
    fontWeight: "600",
    fontSize: 13,
  },
  requestCard: {
    backgroundColor: "rgba(26, 36, 55, 0.7)",
    borderRadius: 16,
    marginBottom: 16,
    overflow: "hidden",
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  cardBlur: {
    padding: 18,
  },
  requestHeader: {
    flexDirection: "row",
    marginBottom: 12,
  },
  requestInfo: {
    flex: 1,
    justifyContent: "center",
  },
  requestTimeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  requestTime: {
    color: colors.lightGray,
    fontSize: 12,
  },
  messageContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    position: "relative",
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  quoteBar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: colors.primary,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
  },
  message: {
    color: colors.white,
    fontSize: 14,
    fontStyle: "italic",
    lineHeight: 20,
  },
  actionButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  acceptButton: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    flex: 1,
    marginLeft: 10,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  rejectButton: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    flex: 1,
    marginRight: 10,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  buttonText: {
    color: colors.white,
    fontWeight: "600",
    fontSize: 14,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  buttonIcon: {
    marginRight: 8,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
    marginBottom: 400,
  },
  emptyIcon: {
    marginTop: 150,
    marginBottom: 16,
    height: 120
  },
  emptyText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
  },
  emptySubtext: {
    color: colors.lightGray,
    fontSize: 14,
    textAlign: "center",
    marginTop: 8,
  },
});
